<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Models.cs" Link="Models.cs" />
    <Compile Include="..\..\NavigatorSettings.cs" Link="NavigatorSettings.cs" />
    <Compile Include="..\..\SearchEngine.cs" Link="SearchEngine.cs" />
  </ItemGroup>
</Project>
